---
title: "The Spatial Distribution of Farmer's Markets in Philadelphia"
author: "Akira Di Sandro, Sofia Fasullo, Amy Solano"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/MUSA5000_Stats/hw04")

#install.packages(c("sp", "ISLR", "MASS", "spatstat", "spatial", "maptools", "ppp", "fossil", "adehabitatHR", "gdata", "raster", "rgdal", "spatialEco", "spatstat.explore", "spatstat.model", "proxy", "sf"))

library(graphics)
library(spatstat)
library(sp)
library(sf)
library(fossil)
library(spatial)
library(adehabitatHR)
library(gdata)
library(raster)
library(spatialEco)
library(spatstat.model)
library(spatstat.explore)
library(proxy)
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)

options(scipen=999)
```


```{r load_data}
farmers_market <- st_read("data/Philadelphia_Farmers_Markets201302.shp", quiet = T)

philly_zips <- st_read("data/Philadelphia_ZipCodes.shp", quiet = T)

philly <- st_read("data/Philadelphia.shp", quiet = T)

```


```{r farmers_markets_points}
farmers_points <- data.frame(farmers_market %>% 
  st_coordinates()) %>%
  distinct()

philly_bound <- as.owin(philly)

# define ppp object
FM_ppp <- ppp(farmers_points$X, farmers_points$Y, window = philly_bound)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
plot(density(FM_ppp))
contour(density(FM_ppp), add=TRUE)
plot(FM_ppp, add=T)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
nnd <- nndist.ppp(FM_ppp)
#Average Observed Distance
MeanObsDist <- mean(nnd)  
#Average Expected Distance
MeanExpDist <- 0.5 / sqrt(nrow(farmers_points) / area.owin(philly_bound))
#Standard Error
SE <- 0.26136 / sqrt(nrow(farmers_points)*nrow(farmers_points) / area.owin(philly_bound))
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
zscore <- (MeanObsDist - MeanExpDist)/SE                    #Calculating the z-score
pval<-ifelse(zscore > 0, 1 - pnorm(zscore), pnorm(zscore))  #Calculating the p-value
zscore
pval
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
NNI <- MeanObsDist / MeanExpDist
NNI
```
```{r}
farmers_distinct <- farmers_market %>% distinct(geometry)
spatialEco::nni(farmers_distinct,win="hull")
```


```{r kFunction} 
# find max distance between points
max.distance <- max(proxy::dist(data.frame(cbind(x=farmers_points$X, y=farmers_points$Y)),
                                data.frame(cbind(x=farmers_points$X, y=farmers_points$Y)),
                                method="euclidean"))
# max.distance  # 56698.31

# approximate 56,698.31 to be about 57,000 and dived that by 2 to get rmax
rmax <- 57000 / 2 # 28500

# define khat
khat <-Kest(FM_ppp, 
            rmax = rmax, 
            correction = "best")

# calculate Ripley's Simulation Confidence Envelopes
Kenv <- spatstat.explore::envelope(FM_ppp,
                                   fun = "Kest", 
                                   rmax = rmax,
                                   nsim = 99,
                                   nrank = 1) 

```

```{r plotKFunction}
# plot Ripley's K-function with Edge correction
plot(khat$r, khat$iso, 
     xlab = "r", ylab = "best k",
     main = "Machine Best Estimated K-Function",
     cex.lab = 1.6, cex.axis = 1.5, cex.main = 1.5,
     lty = 1, lwd = 2)
lines(khat$r, khat$theo, 
      lty = 8, lwd = 2) 

# plot Ripley's K-function with 90% simulation envelopes
plot(Kenv,
     xlab = "r", ylab = "Khat(r)", 
     cex.lab = 1.6, cex.axis = 1.5,
     main = "Machine Best with Confidence Envelopes",
     cex.main = 1.5, lwd = 2)

```
```{r LFunction}
# L Function
lhat <- Lest(FM_ppp,
             rmax = rmax,
             correction = "best")

# L Function with 90% envelopes
Lenv <- spatstat.explore::envelope(FM_ppp,
                                   fun = "Lest",
                                   rmax = rmax,
                                   nsim = 99,
                                   nrank = 1)

```


```{r plotLFunction}
# plot Ripley's L-function
plot(lhat$r, lhat$iso - lhat$r, 
     xlab = "r", ylab = "best L",
     cex.lab = 1.6, cex.axis = 1.5, cex.main = 1.5, 
     lty = 1, lwd = 2, 
     main="best Estimated L-Function") 
lines(lhat$r, lhat$theo - lhat$r, 
      lty = 8, lwd = 2) 

# plot Ripley's L-function with 90% simulation envelopes
plot(Lenv,
     xlab = "r", ylab = "Lhat(r)", 
     cex.lab = 1.6, cex.axis = 1.5,
     main = "best L-function with Confidence Envelopes",
     cex.main = 1.5, lwd = 2)
```

```{r LFunction_prettierplot}
L2 <- Lenv 
L2$obs <- L2$obs-L2$r
L2$theo <- L2$theo-L2$r
L2$lo <- L2$lo-L2$r
L2$hi <- L2$hi-L2$r

plot(L2,
     xlab = "r", ylab = "Lhat(r)", 
     cex.lab = 1.6, cex.axis = 1.5,
     main = "best L-function with Confidence Envelopes",
     cex.main = 1.5, lwd = 2, legend = F)
```