---
title: "Spatial Statistics Homework 1"
author: "Akira DiSandro, Sofia Fasullo, Amy Solano"
date: "2024-09-30"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
scipen=999 #avoid scientific notation
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(viridis)
library(kableExtra)
library(sf)
library(gridExtra)
library(DAAG)
library(MASS)

```

## Section 1: Exploratory Analysis

### Importing Data

```{r load data}

filepath = "C:/Users/sofia/Downloads/RegressionData.csv"
housing_data = read.csv(filepath,header=T)
```

### 1.a) Examining data features

```{r examine features}

# looking at median house value, number of houses with people in poverty, percent of people with secondary degrees in households, percent of vacant houses, and percent of single-family houses

mean_MEDHVAL = round(mean(housing_data$MEDHVAL),2)

mean_NBELPOV100 = round(mean(housing_data$NBELPOV100),2)

mean_PCTBACHMOR = round(mean(housing_data$PCTBACHMOR),2)

mean_PCTVACANT = round(mean(housing_data$PCTVACANT),2)

mean_PCTSINGLES = round(mean(housing_data$PCTSINGLES),2)



sd_MEDHVAL = round(sd(housing_data$MEDHVAL),2)

sd_NBELPOV100 = round(sd(housing_data$NBELPOV100),2)

sd_PCTBACHMOR = round(sd(housing_data$PCTBACHMOR),2)

sd_PCTVACANT = round(sd(housing_data$PCTVACANT),2)

sd_PCTSINGLES = round(sd(housing_data$PCTSINGLES),2)


```


```{r compare features}

variable_type <- c('dependent','predictor','predictor','predictor','predictor')

variable <- c('Median House Value', 'Number of Households Living in Poverty', '% of Individuals with Bachelor’s Degrees or Higher', '% of Vacant Houses','% of Single House Units')

mean <- c(mean_MEDHVAL, mean_NBELPOV100, mean_PCTBACHMOR, mean_PCTVACANT, mean_PCTSINGLES)

standard_deviation <- c(sd_MEDHVAL, sd_NBELPOV100, sd_PCTBACHMOR, sd_PCTVACANT, sd_PCTSINGLES)

compare_table <- data.frame(variable_type, variable, mean, standard_deviation)

kable(compare_table) %>% kable_classic()

```

```{r compare feature distributions}

require(gridExtra)

# create histograms using ggplot2 package

hist1 = ggplot(housing_data, aes(x=MEDHVAL))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist2 = ggplot(housing_data, aes(x=NBELPOV100))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist3 = ggplot(housing_data, aes(x=PCTBACHMOR))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist4 = ggplot(housing_data, aes(x=PCTVACANT))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist5 = ggplot(housing_data, aes(x=PCTSINGLES))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

grid.arrange(hist1,hist2,hist3,hist4,hist5, ncol=3)

```

```{r normalize variables}

# by running table(housing_data$variablename==0) can see if observations are 0 by seeing if there exists "true"

# natural log transform variables

housing_data$LNPCTBACHMOR = log(1+housing_data$PCTBACHMOR)
housing_data$LNMEDHVAL = log(housing_data$MEDHVAL)
housing_data$LNNBELPOV100 = log(1+housing_data$NBELPOV100)
housing_data$LNPCTVACANT = log(1+housing_data$PCTVACANT)
housing_data$LNPCTSINGLES = log(1+housing_data$PCTSINGLES)


```


```{r plot log transformed variables}

require(gridExtra)

# create histograms using ggplot2 package

hist1 = ggplot(housing_data, aes(x=LNMEDHVAL))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist2 = ggplot(housing_data, aes(x=LNNBELPOV100))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist3 = ggplot(housing_data, aes(x=LNPCTBACHMOR))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist4 = ggplot(housing_data, aes(x=LNPCTVACANT))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

hist5 = ggplot(housing_data, aes(x=LNPCTSINGLES))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')

grid.arrange(hist1,hist2,hist3,hist4,hist5, ncol=3)
```

Insert some text about the spike

```{r determine linear relationship}
require(gridExtra)

# later make this prettier

scat1 = ggplot(housing_data, aes(x=LNNBELPOV100, y=LNMEDHVAL))+
   geom_point( color='blue', alpha=0.6)

scat2 = ggplot(housing_data, aes(x=PCTBACHMOR, y=LNMEDHVAL))+
   geom_point( color='blue', alpha=0.6)

scat3 = ggplot(housing_data, aes(x=PCTVACANT, y=LNMEDHVAL))+
   geom_point( color='blue', alpha=0.6)

scat4 = ggplot(housing_data, aes(x=PCTSINGLES, y=LNMEDHVAL))+
   geom_point( color='blue', alpha=0.6)


grid.arrange(scat1,scat2,scat3,scat4, ncol=2)
```


```{r correlation matrix}

predictors = housing_data %>% select(LNNBELPOV100,PCTBACHMOR,PCTVACANT,PCTSINGLES)

cor_matrix = cor(predictors, method='pearson')
kable(cor_matrix) %>% kable_classic()
```

Honestly, none of the correlations look especially high.

```{r correlation matrix}

ggcorrplot(
  round(cor(predictors), 2),
  p.mat = cor_pmat(predictors),
  lab=T,
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation Matrix of Predictor Variables", tl.cex = 0.5, tl.col = "black")
```

```{r import shapefile}

philly = st_read("C:/Users/sofia/Downloads/RegressionDataShp")
```


gotta work on the log display of this one
```{r dependent variable map}

maptheme =   theme(
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.title = element_blank()
  )

ggplot() +
  geom_sf(data = philly, aes(fill=MEDHVAL),colour=NA)+
  scale_fill_viridis(trans="log")+
  labs(title = "Philadelphia Median House Value") +
  theme_minimal() +
  maptheme

```


```{r predictor maps}
require(gridExtra)

# later make this prettier

map1 = ggplot() +
  geom_sf(data = philly, aes(fill=LNNBELPOV),colour=NA)+
  scale_fill_viridis()+
  labs(title = "Number of Households Living in Poverty") +
  theme_minimal() +
  maptheme

map2 = ggplot() +
  geom_sf(data = philly, aes(fill=PCTBACHMOR),colour=NA)+
  scale_fill_viridis()+
  labs(title = "Percent People with Bachelor Degrees") +
  theme_minimal() +
  maptheme

map3 = ggplot() +
  geom_sf(data = philly, aes(fill=PCTVACANT), color=NA)+
  scale_fill_viridis()+
  labs(title = "Percent Vacancy") +
  theme_minimal() +
  maptheme

map4 = ggplot() +
  geom_sf(data = philly, aes(fill=PCTSINGLES),color=NA)+
  scale_fill_viridis()+
  labs(title = "Percent Single Family Housing") +
  theme_minimal() +
  maptheme


grid.arrange(map1,map2,map3,map4, ncol=2)
```

## Part 2: Linear Regression

```{r multiple linear regression}

mlm = lm(data=housing_data,LNMEDHVAL~LNNBELPOV100+PCTBACHMOR+PCTVACANT+PCTSINGLES)

summary(mlm)
anova(mlm)

```


```{r multiple linear model results}

predictedy = fitted(mlm)
residuals = residuals(mlm)
st_resids = rstandard(mlm)
```

```{r plot residuals over change in y}

ggplot() +
  geom_point(aes(x=predictedy,y=st_resids))
```

```{r stepwise model}

stepmod = step(mlm, direction="both")
```

```{r stepwise model results}

kable(stepmod$anova) %>% kable_classic()
```



```{r cross validation}

cvresult<- cv.lm(data = housing_data, form.lm = mlm, m=5)


```


```{r cross validation on a simpler model}

mlm2= lm(LNMEDHVAL~ PCTVACANT+MEDHHINC, data = housing_data)

cvresult2<- cv.lm(data = housing_data, form.lm = mlm2, m=5)

```

```{r plotting residuals}

residualsdf = as.data.frame(residuals)

ggplot(data=residualsdf,aes(x=residuals))+
   geom_histogram( fill='blue', alpha=0.6, position='identity')
```
looks normally distributed!

## Next section



