---
title: "Predicting Median House Value in Philadelphia"
author: "Akira Di Sandro, Sofia Fasullo, Amy Solano"
date: "2024-10-14"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, warning = F, message = F)

# get rid of scientific notation
options(scipen = 999)

# load appropriate packages
library(tidyverse)
library(sf)
library(FNN)
library(grid)
library(gridExtra)
library(kableExtra)
library(ggcorrplot)
library(rmarkdown)
library(pander)
library(Hmisc)
library(car)
library(DAAG)
library(MASS)
```

# Introduction

**intro paragraphs**

```{r load_data}
regdata <- read.csv("RegressionData.csv")
regshp <- st_read("Lecture 1 - RegressionData.shp/RegressionData.shp")

```

# Methods

## Data Cleaning


## Exploratory Data Analysis

[describe variables]

[formula for sample correlation coefficient]

## Multiple Regression Analysis

[specific regression equation for this problem]

[state hypothesis being tested]

## Additional Analyses

[stepwise regression]

[k-fold cross-validation]

## Software


# Results

## Exploratory Results

### Summary Statistics of Variables

[describe summary stats]

```{r sum_stats}
sumstats <- regdata %>% 
  summarise(
    mean_MEDHVAL = mean(MEDHVAL),
    sd_MEDHVAL = sd(MEDHVAL),
    mean_PCTBACHMOR = mean(PCTBACHMOR),
    sd_PCTBACHMOR = sd(PCTBACHMOR),
    mean_MEDHHINC = mean(MEDHHINC),
    sd_MEDHHINC = sd(MEDHHINC),
    mean_PCTVACANT = mean(PCTVACANT),
    sd_PCTVACANT = sd(PCTVACANT),
    mean_PCTSINGLES = mean(PCTSINGLES),
    sd_PCTSINGLES = sd(PCTSINGLES),
    mean_NBELPOV100 = mean(NBELPOV100),
    sd_NBELPOV100 = sd(NBELPOV100),
    )
    
means <- sumstats %>% 
  pivot_longer(cols = all_of(starts_with("mean_")),
               names_to = "variable",
               values_to = "Mean",
               names_prefix = "mean_") %>% 
  dplyr::select(variable:Mean)


sds <- sumstats %>% 
  pivot_longer(cols = all_of(starts_with("sd_")),
               names_to = "variable",
               values_to = "SD",
               names_prefix = "sd_") %>% 
  dplyr::select(variable:SD)

# create a clean dataframe for table
sumstats_tab <- left_join(means, sds, by = "variable") %>% 
  rename(rowname = 1) %>% 
  column_to_rownames() %>% 
  t() %>% 
  data.frame() %>% 
  mutate(`Median House Value (MEDHVAL)` = paste0("$",format(round(MEDHVAL, 2), big.mark = ",", nsmall = 2)),
         `Pct Bachelor or more (PCTBACHMOR)` = paste0(format(round(PCTBACHMOR, 1), nsmall = 1), "%"),
         `Median Household Income (MEDHHINC)` = paste0("$",format(round(MEDHHINC, 2), big.mark = ",", nsmall = 2)),
         `Pct Vacant (PCTVACANT)` = paste0(format(round(PCTVACANT, 1), nsmall = 1), "%"),
         `Pct Single Unit (PCTSINGLES)` = paste0(format(round(PCTSINGLES, 1), nsmall = 1), "%"),
         `Units Below Poverty level (NBELPOV100)` = format(round(NBELPOV100), nsmall = 0),
         .keep = "unused") %>% 
  t() %>% 
  data.frame() %>% 
  rownames_to_column(var = "Variable")
 
sumstats_tab %>% 
  kbl(caption = "Table 1. Summary Statistics of Dependent and Independent Variables",
      align = "lcc") %>% 
  kable_styling() %>%
  kable_classic(full_width = F, html_font = "Cambria") 

```

### Variable Histograms

[normality of variables]

```{r histograms_setup}
# MEDHVAL
hist_medhval <- ggplot(regdata) +
  geom_histogram(aes(x = MEDHVAL), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Median House Value",
       y = "Count") +
  scale_x_continuous(labels = scales::dollar)

# PCTBACHMOR
hist_pctbach <- regdata %>% 
  mutate(PCTBACHMOR = PCTBACHMOR / 100) %>% 
  ggplot() +
  geom_histogram(aes(x = PCTBACHMOR), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "% residents with at least\na Bachelor's Degree",
       y = "Count") +
  scale_x_continuous(labels = scales::percent)

# MEDHHINC
hist_medhhinc <- ggplot(regdata) +
  geom_histogram(aes(x = MEDHHINC), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Median Household Income",
       y = "Count") +
  scale_x_continuous(labels = scales::dollar)

# PCTVACANT
hist_pctvac <- regdata %>% 
  mutate(PCTVACANT = PCTVACANT / 100) %>% 
  ggplot() +
  geom_histogram(aes(x = PCTVACANT), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "% housing units that are vacant",
       y = "Count") +
  scale_x_continuous(labels = scales::percent)

# PCTSINGLES
hist_pctsing <- regdata %>% 
  mutate(PCTSINGLES = PCTSINGLES / 100) %>% 
  ggplot() +
  geom_histogram(aes(x = PCTSINGLES), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "% housing units that are detached\nsingle family houses",
       y = "Count") +
  scale_x_continuous(labels = scales::percent)

# NBELPOV100
hist_nbelpov <- ggplot(regdata) +
  geom_histogram(aes(x = NBELPOV100), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "# of households living in poverty",
       y = "Count")

# log-transformed variables
regdata_log <- regdata %>% 
  mutate(LNMEDHVAL = log(MEDHVAL),
         LNPCBACHMORE = log(1 + PCTBACHMOR),
         LNNBELPOV100 = log(1 + NBELPOV100),
         LNPCTVACANT = log(1 + PCTVACANT),
         LNPCTSINGLES = log(1 + PCTSINGLES),
         LNMEDHHINC = log(MEDHHINC))

# LNMEDHVAL
hist_lnmedhval <- ggplot(regdata_log) +
  geom_histogram(aes(x = LNMEDHVAL), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed Median House Value",
       y = "Count")

# log PCTBACHMOR
hist_lnpctbach <- regdata_log %>% 
  ggplot() +
  geom_histogram(aes(x = LNPCBACHMORE), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed % residents with at\nleast a Bachelor's Degree",
       y = "Count")
      
# log MEDHHINC
hist_lnmedhhinc <- ggplot(regdata_log) +
  geom_histogram(aes(x = LNMEDHHINC), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed Median Household Income",
       y = "Count")

# log PCTVACANT
hist_lnpctvac <- regdata_log %>% 
  ggplot() +
  geom_histogram(aes(x = LNPCTVACANT), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed % housing units that are vacant",
       y = "Count")
      
# log PCTSINGLES
hist_lnpctsing <- regdata_log %>% 
  ggplot() +
  geom_histogram(aes(x = LNPCTSINGLES), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed % housing units that are\ndetached single family houses",
       y = "Count")
      
# log NBELPOV100
hist_lnnbelpov <- ggplot(regdata_log) +
  geom_histogram(aes(x = LNNBELPOV100), fill = "#451077FF") +
  theme_minimal() +
  labs(x = "Log-transformed # of households\nliving in poverty",
       y = "Count")


```


```{r medhval_hist}
# histogram of raw and log-transformed medhval
grid.arrange(hist_medhval, hist_lnmedhval,
             ncol = 2,
             top = textGrob("Distribution of MEDHVAL: Median House Value\n(raw and log-transformed)", 
                            gp = gpar(fontsize = 16, fontface = "bold")))
    

```


```{r pcbach_hist}
# histogram of raw and log-transformed medhval
grid.arrange(hist_pctbach, hist_lnpctbach,
             ncol = 2,
             top = textGrob("Distribution of PCTBACH: Proportion of residents with\nat least a Bachelor's Degree (raw and log-transformed)", 
                            gp = gpar(fontsize = 16, fontface = "bold")))
    

```


```{r nbelpov_hist}
# histogram of raw and log-transformed nbelpov100
grid.arrange(hist_nbelpov, hist_lnnbelpov,
             ncol = 2,
             top = textGrob("Distribution of NBELPOV100: Number of households living\nin poverty (raw and log-transformed)",
                            gp = gpar(fontsize = 16, fontface = "bold")))
    

```


```{r pctvac_hist}
# histogram of raw and log-transformed pctvacant
grid.arrange(hist_pctvac, hist_lnpctvac,
             ncol = 2,
             top = textGrob("Distribution of PCTVACANT: Proportion of housing units\nthat are vacant (raw and log-transformed)",
                            gp = gpar(fontsize = 16, fontface = "bold")))
    

```


```{r pctsing_hist}
# histogram of raw and log-transformed PCTSINGLES
grid.arrange(hist_pctsing, hist_lnpctsing,
             ncol = 2,
             top = textGrob("Distribution of PCTSINGLES: Percent of housing units that are\ndetached single family houses (raw and log-transformed)",
                            gp = gpar(fontsize = 16, fontface = "bold")))
    

```


### Chloropleth Maps

```{r chloropleth_setup}
chloro_lnmedhval <- regshp %>%
  ggplot() +
  geom_sf(aes(fill = LNMEDHVAL)) +
  theme_void() +
  scale_fill_viridis_c(option = "magma",
                       name = "Log Med. House Val.",
                       na.value = "grey") +
  labs(title = "Median House Values (log-transformed) in Philadelphia")

# PCTVACANT
chloro_pctvac <- regshp %>% 
  ggplot() +
  geom_sf(aes(fill = PCTVACANT), color = "transparent") +
  theme_void() +
  scale_fill_viridis_c(option = "magma",
                       name = "Pct Vacant",
                       na.value = "grey",
                       limits = c(0, 100)) +
  labs(title = "% housing units that are vacant")

# PCTSINGLES
chloro_pctsing <- regshp %>% 
  ggplot() +
  geom_sf(aes(fill = PCTSINGLES), color = "transparent") +
  theme_void() +
  scale_fill_viridis_c(option = "magma",
                       name = "Pct Single Unit",
                       na.value = "grey",
                       limits = c(0, 100)) +
  labs(title = "% housing units that are detached\nsingle family houses")

# PCTBACHMOR
chloro_pctbach <- regshp %>% 
  ggplot() +
  geom_sf(aes(fill = PCTBACHMOR), color = "transparent") +
  theme_void() +
  scale_fill_viridis_c(option = "magma",
                       name = "Pct Bach.",
                       na.value = "grey",
                       limits = c(0, 100)) +
  labs(title = "% residents with at least a Bachelor's Degree")

# LNNBELPOV
chloro_lnnbelpov <- regshp %>% 
  ggplot() +
  geom_sf(aes(fill = LNNBELPOV), color = "transparent") +
  theme_void() +
  scale_fill_viridis_c(option = "magma",
                       name = "Log Units",
                       na.value = "grey",
                       limits = c(0, 8)) +
  labs(title = "# of households living in poverty (log-transformed)")

```


```{r medhval_chloro}

```


```{r predictors_chloro, fig.height=10}
# display all four figures in one
grid.arrange(chloro_pctbach, chloro_pctvac, chloro_pctsing, chloro_lnnbelpov,
             ncol = 2,
             top = textGrob("Chloropleth Maps of Predictors", 
                            gp = gpar(fontsize = 16, fontface = "bold")))
```


### Correlation Matrix

```{r cormat}
cormat <- regdata_log %>% 
  dplyr::select(PCTVACANT,PCTSINGLES,PCTBACHMOR,LNNBELPOV100) %>% 
  cor()

cor_plot <- ggcorrplot(cormat,
                       method = "circle",
                       type = "lower",
                       lab = TRUE,
                       lab_size = 3,
                       colors = c("#451077FF", "white", "#F1605DFF"),
                       outline.color = "white",
                       title = "Correlation Matrix of Predictors",
                       legend.title = "Correlation") +
  theme_minimal() +  
  labs(x = "",
       y = "") +
  theme(axis.text.x = element_text(angle = 20))

cor_plot

```

